### ISSUE TITLE
Multi-disk zip archives not supported

### ISSUE THREAD

**Issue by ChrisPHL** [lemgandi/3mf2stl#2]
I checked out master and built the executable successfully.
When I try to convert a 3mf file 3mf2stl outputs an error: "Multi-disk zip archives not supported".

So optimum case would be to extract and re-zip the *.3mf file automatically, of course.
But maybe you output an advice for the user additionally to the error message, how to workaround that error on command line.

Kind regards
Christian

**Comment by lemgandi** [comment]
Please read the documentation for information on this error. The short
answer is **use the shell script **  ( convert_to_stl.sh).

-- CHS
